### ISSUE TITLE
인풋 길이 제한이 궁금합니다.

### ISSUE THREAD

**Issue by heunggyulee** [cosmoquester/2021-dialogue-summary-competition#24]
안녕하세요. 
좋은 코드 공유해주셔서 감사합니다. :)

혹시 인풋 길이 제한은 어떻게 될까요?!

**Comment by cosmoquester** [comment]
저희가 학습시켜서 공유한 모델을 말씀하시는 거라면 input dialogue는 256 토큰, sumary는 64토큰을 사용했네요! 
https://github.com/cosmoquester/2021-dialogue-summary-competition/blob/aca1b0f6f5b2eb3066cd5ba8a70dc41e0126b469/run/train.py#L33-L34

따로 학습을 시키실 예정이라면 원하는 길이를 사용하시면 됩니다.

**Comment by heunggyulee** [comment]
감사합니다 :)
