### ISSUE TITLE
sample data를 보고 학습을 할 때 어떻게 한것인지 질문이있어 올립니다.

### ISSUE THREAD

**Issue by sgr1118** [cosmoquester/2021-dialogue-summary-competition#25]
dialogue에 json에서 추출한 utterance들을 모아놓은 것을 봤습니다.
sample에서 iloc[0]을 사용하면 '["밥 먹었어~?", "편의점에서 대충 때웠어", "허어얼.. 편의점이라니", "#@이모티콘#"]' 이렇게 뜹니다. iloc[0][0]이라고하면 '['만 나옵니다. 학습을 할 때 '[', ']'이런것들은 전부 지우신건가요?

**Comment by cosmoquester** [comment]
음... iloc[0]을 사용한다는 게 무슨 뜻인지 잘 모르겠네요?
json데이터를 읽어 처리하는 부분은 [summarizer/data.py](https://github.com/cosmoquester/2021-dialogue-summary-competition/blob/master/summarizer/data.py) 에서 확인하실 수 있습니다!
