### ISSUE TITLE
안녕하세요! 모델 학습을 위한 데이터 양식에 대해 질문드립니다.

### ISSUE THREAD

**Issue by Youngseo-Jeon0313** [cosmoquester/2021-dialogue-summary-competition#26]
안녕하세요, 좋은 코드 공유해주셔서 감사합니다!
해당 모델로 학습해보려고 하는데 [해당 코드](https://github.com/cosmoquester/2021-dialogue-summary-competition/blob/master/summarizer/data.py) 를 살펴보며 궁금한 점이 있어서 문의 드립니다 ! 
제가 알기로는 AIHub 데이터를 이용해서 학습한 것으로 알고 있는데 혹시 해당 AIHUB 데이터에 맞춘 JSON 형식을 사용해야 하는지, 아니면 아래와 같은 형식으로 학습을 해야 하는지 궁금합니다!
`id    dialogue                                      summary
1     ["안녕하세요", "안녕하세요 반갑습니다."]            "인사하는 대화"
2     ["오늘 날씨가 참 좋네요.", "맞아요. 기분이 좋아지는 날씨죠."]   "날씨 칭찬 대화"
3     ["종각에서 만나자.", "좋아요. 어떤 음식이 먹고 싶어?"]        "만남 약속 대화"
`

**Comment by cosmoquester** [comment]
둘 중 원하는 형식을 사용하시면 됩니다!
https://github.com/cosmoquester/2021-dialogue-summary-competition/blob/aca1b0f6f5b2eb3066cd5ba8a70dc41e0126b469/summarizer/data.py#L139-L141
를 보시면 확장자에 따라 로드를 하게 됩니다
